languageCode = "en-us"
title = "My New Hugo Site"
theme = "eon"
baseURL = "http://localhost:3000/"

[Author]
  name = "Ryan Burnette"
  email = "ryan.burnette@gmail.com"

[Params]
  gravatar = true
  disqus_url = "https://ryanburnette.disqus.com"

[markup.goldmark.renderer]
  unsafe = true
